import Head from 'next/head'
import { useEffect } from 'react'

export default function Home () {
  useEffect(() => {
    window.location.replace(
      '/co'
    )
  }, [])
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
    </div>
  )
}
